# Generated by Django 6.0 on 2026-02-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labreport',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='labreport',
            name='test_results',
        ),
        migrations.AlterField(
            model_name='labreport',
            name='category',
            field=models.CharField(choices=[('hematology', 'Hematology'), ('biochemistry', 'Biochemistry'), ('endocrinology', 'Endocrinology'), ('microbiology', 'Microbiology'), ('pathology', 'Pathology'), ('radiology', 'Radiology'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('normal', 'Normal'), ('abnormal', 'Abnormal'), ('critical', 'Critical')], default='pending', max_length=20),
        ),
    ]
