# Generated by Django 6.0 on 2026-02-16 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_sharedconsultation'),
        ('staff', '0002_remove_labreport_doctor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labreport',
            options={},
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='labreport',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_lab_reports', to='doctors.doctorprofile'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photos/'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='category',
            field=models.CharField(choices=[('hematology', 'Hematology'), ('biochemistry', 'Biochemistry'), ('endocrinology', 'Endocrinology'), ('microbiology', 'Microbiology'), ('radiology', 'Radiology'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='report_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal'), ('critical', 'Critical')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='test_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_reports', to='staff.staffprofile'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_id',
            field=models.CharField(blank=True, default='STF-0', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LabReportParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('normal_range', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Normal', 'Normal'), ('High', 'High'), ('Low', 'Low')], default='Normal', max_length=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='staff.labreport')),
            ],
        ),
    ]
