# Generated by Django 6.0 on 2026-02-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_labreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_id',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
    ]
