# Generated by Django 6.0 on 2026-02-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_labreport_is_completed_alter_staffprofile_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='report_image',
            field=models.ImageField(blank=True, null=True, upload_to='lab_report_images/'),
        ),
    ]
