# Generated by Django 6.0 on 2026-02-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_labreport_report_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
