# Generated by Django 6.0 on 2026-02-26 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_staffprofile_staff_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labreport',
            old_name='status',
            new_name='overall_status',
        ),
        migrations.RemoveField(
            model_name='labreport',
            name='category',
        ),
        migrations.RemoveField(
            model_name='labreport',
            name='findings',
        ),
        migrations.RemoveField(
            model_name='labreport',
            name='test_name',
        ),
        migrations.RemoveField(
            model_name='labreportparameter',
            name='report',
        ),
        migrations.AddField(
            model_name='labreport',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TestSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name_choice', models.CharField(blank=True, choices=[('CBC', 'Complete Blood Count (CBC)'), ('LFT', 'Liver Function Test (LFT)'), ('KFT', 'Kidney Function Test (KFT)'), ('Lipid Profile', 'Lipid Profile'), ('Thyroid Panel', 'Thyroid Function Test'), ('HbA1c', 'HbA1c (Diabetes)'), ('Urinalysis', 'Urinalysis'), ('ESR', 'Erythrocyte Sedimentation Rate (ESR)'), ('CRP', 'C-Reactive Protein (CRP)'), ('Vitamin D', 'Vitamin D'), ('Vitamin B12', 'Vitamin B12'), ('Iron Studies', 'Iron Studies'), ('Electrolytes', 'Electrolytes'), ('Blood Gas', 'Arterial Blood Gas (ABG)'), ('Coagulation', 'Coagulation Panel'), ('Other', 'Other (Custom)')], max_length=50, null=True)),
                ('custom_test_name', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(choices=[('hematology', 'Hematology'), ('biochemistry', 'Biochemistry'), ('endocrinology', 'Endocrinology'), ('microbiology', 'Microbiology'), ('radiology', 'Radiology'), ('other', 'Other')], default='other', max_length=50)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('findings', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sections', to='staff.labreport')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='labreportparameter',
            name='test_section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='staff.testsection'),
            preserve_default=False,
        ),
    ]
