# Generated by Django 6.0 on 2026-02-28 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_rename_status_labreport_overall_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='lab_report_files/')),
                ('attachment_type', models.CharField(choices=[('document', 'Document'), ('image', 'Image')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='staff.labreport')),
            ],
            options={
                'db_table': 'staff_lab_report_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
