# Generated by Django 6.0 on 2026-03-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_labreportattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='certification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(blank=True, default='Lab Technician', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='shift',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='years_of_experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
