# Generated by Django 6.0 on 2026-03-04 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_alter_consultationhistory_appointment'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicineschedule',
            options={},
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='is_available',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='price_per_unit',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='medicineschedule',
            name='special_instructions',
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('antibiotic', 'Antibiotic'), ('painkiller', 'Painkiller'), ('antiviral', 'Antiviral'), ('antifungal', 'Antifungal'), ('vitamin', 'Vitamin/Supplement'), ('cardiac', 'Cardiac'), ('diabetes', 'Diabetes'), ('respiratory', 'Respiratory'), ('gastrointestinal', 'Gastrointestinal'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='reorder_level',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='side_effects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='storage_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='department',
            field=models.CharField(blank=True, default='Pharmacy', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='pharmacy_photos/'),
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='shift',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='years_of_experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quantity_in_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='unit_type',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('drops', 'Drops'), ('cream', 'Cream'), ('inhaler', 'Inhaler'), ('other', 'Other')], default='tablet', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicineschedule',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.medicine'),
        ),
        migrations.AlterField(
            model_name='medicineschedule',
            name='prescribed_medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.prescribedmedicine'),
        ),
        migrations.AlterField(
            model_name='medicineschedule',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_schedules', to='doctors.prescription'),
        ),
        migrations.AlterField(
            model_name='medicineschedule',
            name='remaining_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicineschedule',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicineschedule',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
