# Generated by Django 6.0 on 2026-03-06 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_alter_consultationhistory_appointment'),
        ('pharmacy', '0002_alter_medicineschedule_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyFulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Assignment'), ('fulfilled', 'Fully Fulfilled'), ('partial', 'Partially Fulfilled'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled by Patient')], default='pending', max_length=20)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacy_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfillments', to='pharmacy.pharmacyprofile')),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_fulfillment', to='doctors.prescription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FulfilledMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_dispensed', models.IntegerField()),
                ('quantity_requested', models.IntegerField()),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('prescribed_medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.prescribedmedicine')),
                ('stock_medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.medicine')),
                ('fulfillment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfilled_medicines', to='pharmacy.pharmacyfulfillment')),
            ],
        ),
    ]
