# Generated by Django 6.0 on 2026-01-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='is_active',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='patient_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
