# Generated by Django 6.0 on 2026-01-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patientprofile_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='patient_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
