# Generated by Django 6.0 on 2026-02-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
