# Generated by Django 6.0 on 2026-02-06 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctorprofile_consultation_fee_and_more'),
        ('patients', '0008_patientprofile_city_patientprofile_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('consultation_date', models.DateField()),
                ('consultation_time', models.TimeField()),
                ('consultation_type', models.CharField(choices=[('new_visit', 'New Visit'), ('follow_up', 'Follow-up'), ('emergency', 'Emergency'), ('routine_checkup', 'Routine Checkup')], default='new_visit', max_length=20)),
                ('chief_complaint', models.TextField()),
                ('diagnosis', models.TextField()),
                ('symptoms', models.TextField(help_text='Comma-separated symptoms')),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('heart_rate', models.CharField(blank=True, max_length=20, null=True)),
                ('temperature', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('height', models.CharField(blank=True, max_length=20, null=True)),
                ('examination_findings', models.TextField(blank=True, null=True)),
                ('treatment_plan', models.TextField()),
                ('prescription_issued', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_history', to='doctors.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_histories', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_histories', to='patients.patientprofile')),
            ],
            options={
                'verbose_name_plural': 'Consultation Histories',
                'ordering': ['-consultation_date', '-consultation_time'],
            },
        ),
    ]
