# Generated by Django 6.0 on 2026-02-07 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_doctorprofile_available_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='consultationhistory',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_history', to='doctors.appointment'),
        ),
        migrations.AlterField(
            model_name='consultationhistory',
            name='symptoms',
            field=models.TextField(blank=True, help_text='Comma-separated symptoms'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prescribedmedicine',
            name='instructions',
            field=models.TextField(blank=True),
        ),
    ]
