# Generated by Django 6.0 on 2026-02-08 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_doctorprofile_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='consultation_fee',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='years_of_experience',
        ),
    ]
