# Generated by Django 6.0 on 2026-02-15 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_appointment_reminder_sent_alter_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_records', to='doctors.consultationhistory')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_shared_by_me', to='doctors.doctorprofile')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_shared_with_me', to='doctors.doctorprofile')),
            ],
            options={
                'ordering': ['-shared_at'],
                'unique_together': {('consultation', 'shared_by', 'shared_with')},
            },
        ),
    ]
