# Generated by Django 6.0 on 2026-02-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_sharedconsultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('follow-up', 'Follow-up'), ('check-up', 'Check-up')], max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('missed', 'Missed'), ('needs_rescheduling', 'Needs Rescheduling')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='consultationhistory',
            name='consultation_type',
            field=models.CharField(choices=[('new_visit', 'New Visit'), ('follow_up', 'Follow-up')], default='new_visit', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='slot_type',
            field=models.CharField(choices=[('consultation', 'Consultation')], default='consultation', max_length=20),
        ),
        migrations.DeleteModel(
            name='BlockedTimeSlot',
        ),
    ]
