# Generated by Django 6.0 on 2026-03-03 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_alter_doctorprofile_available_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationhistory',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_histories', to='doctors.appointment'),
        ),
    ]
